---
  - hosts: databases
    become: true
    gather_facts: no
    tasks:
      - name: Create key pair in pg-primary and pg-standby
        #become: true  
        become_user: postgres
        file:
          path: /var/lib/postgresql/.ssh
          state: directory
          owner: postgres
          group: postgres
          mode: 0700
      - command: ssh-keygen -f /var/lib/postgresql/.ssh/id_rsa -t rsa -b 4096 -N ""
        args:
          creates: /var/lib/postgresql/.ssh/id_rsa
      - name: Copy pg-primary public key to repository
        command: cat /var/lib/postgresql/.ssh/id_rsa.pub
        register: db_ssh_keys
      - name: right for files
        file: 
          path: /var/lib/postgresql/.ssh/{{ item }}
          owner: postgres
          group: postgres 
        with_items:
        - id_rsa
        - id_rsa.pub 
      - name: Allow passwordless SSH for repo
        #become: true
        become_user: pgbackrest
        lineinfile:
          create: yes
          dest: /home/pgbackrest/.ssh/authorized_keys
          state: present
          line: '{{ item }}'
        with_items: '{{ db_ssh_keys.stdout }}'
        delegate_to: pg-repo01


  - hosts: repository
    become: true
    vars:
      db:
        - pg-prim01
        - pg-std01
    tasks:

      - name: Create repository host key pair
        #become: true
        become_user: pgbackrest
        file:
          path: /home/pgbackrest/.ssh
          state: directory
          owner: pgbackrest
          group: pgbackrest
          mode: 0700
      - command: ssh-keygen -f /home/pgbackrest/.ssh/id_rsa -t rsa -b 4096 -N ""
        args:
          creates: /home/pgbackrest/.ssh/id_rsa
      - name: Copy repository public key to pg-primary and pg-standby
        command: cat /home/pgbackrest/.ssh/id_rsa.pub
        register: repo_ssh_keys
      - name: right for files
        file: 
          path: /home/pgbackrest/.ssh/{{ item }}
          owner: pgbackrest
          group: pgbackrest 
        with_items:
        - id_rsa
        - id_rsa.pub 
      - name: Allow passwordless SSH for dbs
        #become: true
        become_user: postgres
        lineinfile:
          create: yes
          dest: /var/lib/postgresql/.ssh/authorized_keys
          state: present
          line:  " {{repo_ssh_keys.stdout}}"
        delegate_to: '{{ item }}'
        loop: '{{ db }}'
