---
- hosts: all
  become: true
  vars_files:
    - vars/varsfiles.yml 
  pre_tasks:
    - name: "Install packages"
      ansible.builtin.apt:
        name: 
          - postgresql-{{ postgresql_version }}
          - python3-psycopg2
        state: present
  tasks:
    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "{{ postgresql_data_dir }}/pg_hba.conf"
      register: postgres_data
    - name: Initialize PostgreSQL
      ansible.builtin.shell: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
      become: true
      become_user: postgres
      when: not postgres_data.stat.exists

    - name: Start and enable service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
